// gen_content_review.js — regenerates CONTENT_REVIEW.md from CCSM_SeedContent.gs
// so the human-review document can never drift from the content that actually
// ships: it runs the real seeders against the in-memory fixture sheet and
// renders exactly the rows they produced.
//
//   cd "<CCSM project root>" && node tools/gen_content_review.js
//
// Must be run from the project root — the GAS stub harness resolves .gs files
// relative to the working directory.
const fs = require('fs');
const { makeGasEnv } = require('../tests/gas_stubs');
const { loadGs } = require('../tests/load_gs');
const { makeCcsmSpreadsheet } = require('../tests/fixtures');

const env = makeGasEnv();
const scope = loadGs(
  ['CcsmData.gs', 'BuildCcsmSheet.gs', 'CCSM_Helpers.gs', 'CCSM_AgentTestMode.gs', 'CCSM_Agent1A.gs',
   'CCSM_SeedContent.gs', 'CCSM_Agent1C.gs'],
  env.globals
);
const ss = makeCcsmSpreadsheet(env, scope);
scope.seedCcsmMessageBank();
scope.seedCcsmKnowledgeBase();

function read(tab) {
  const d = ss.getSheetByName(tab).getDataRange().getValues();
  const h = d[0].map(String);
  return d.slice(1).map((r) => { const o = {}; h.forEach((k, i) => (o[k] = String(r[i] === undefined ? '' : r[i]))); return o; });
}
const mb = read('MESSAGE_BANK');
const kb = read('KNOWLEDGE_BASE');

const refs = {};
mb.forEach((r) => { if (r.Scripture) { refs[r.Scripture] = refs[r.Scripture] || { blank: 0, total: 0 }; refs[r.Scripture].total++; if (!r.Scripture_Text) refs[r.Scripture].blank++; } });

const display = {};
scope.CCSM_NIGHTLY_QUESTIONS.forEach((q) => (display[q.key] = q.displayEs));
scope.A1A_RATE_METRICS.forEach((m) => (display[m.key] = m.display));

const CATS = [
  ['SUNDAY_COACHING_STRENGTH', 'Domingo — Fortaleza (SUNDAY_COACHING_STRENGTH)', 'Se envía cuando el área tuvo un buen resultado en esa métrica.'],
  ['SUNDAY_COACHING_GROWTH', 'Domingo — Crecimiento (SUNDAY_COACHING_GROWTH)', 'Se envía cuando el área necesita mejorar en esa métrica.'],
  ['FRIDAY_ENCOURAGEMENT', 'Viernes — Ánimo (FRIDAY_ENCOURAGEMENT)', 'Empujón de media semana hacia la meta semanal de conteo.'],
  ['MISSED_DAYS', 'Informes faltantes (MISSED_DAYS)', 'Se envía cuando un área deja de enviar informes nocturnos.']
];

const out = [];
out.push('# CONTENT_REVIEW — MESSAGE_BANK + KNOWLEDGE_BASE + LEADERSHIP (CCSM)');
out.push('');
out.push('**Launch gate.** The two seeded content banks are listed below, plus the hardcoded');
out.push('leadership messages from `CCSM_Agent1C.gs`.');
out.push('Selection from the banks is *pick-not-generate*: the agents choose a row by ID and send it verbatim.');
out.push('Nothing in the banks is AI-generated at send time.');
out.push('');
out.push('> **Scope warning — read before signing off.** This file used to claim it listed');
out.push('> *every missionary-facing word the system can send*. It did not. The seeded banks');
out.push('> are only part of the outgoing text: individual agents also build subjects and');
out.push('> bodies from hardcoded Spanish templates that were never surfaced here. That gap');
out.push('> is how ten hand-written scripture quotations reached the **leadership** emails');
out.push('> without passing the no-fabrication rule the 193 bank rows were held to.');
out.push('>');
out.push('> The leadership messages are now included below. The remaining per-agent');
out.push('> templates — reminder, escalation, validation and duplicate notices — are still');
out.push('> NOT listed here and still need a Spanish read.');
out.push('');
out.push('`TEST_MODE` must stay `TRUE` until this review is signed off. Ideally reviewed by a native Spanish');
out.push('speaker and by mission leadership.');
out.push('');
out.push('Generated from `CCSM_SeedContent.gs` and `CCSM_Agent1C.gs` — do not edit this file by hand.');
out.push('Edit the `.gs` and regenerate with `node tools/gen_content_review.js`.');
out.push('');
out.push('| | |');
out.push('|---|---|');
CATS.forEach(([c]) => out.push('| ' + c + ' | ' + mb.filter((r) => r.Category === c).length + ' filas |'));
out.push('| **Total MESSAGE_BANK** | **' + mb.length + ' filas** |');
out.push('| KNOWLEDGE_BASE | ' + kb.length + ' filas |');
out.push('');
out.push('---');
out.push('');
out.push('## ⚠️ Open questions for the reviewer');
out.push('');
out.push('### 1. Scripture_Text is BLANK on ' + mb.filter((r) => r.Scripture_Text === '').length + ' of ' + mb.length + ' rows — this is the most important review task');
out.push('');
out.push('Scripture *references* were chosen deliberately; scripture *text* was left empty everywhere the exact');
out.push('wording of the Spanish LDS edition could not be guaranteed. A blank cell is intentional and correct —');
out.push('inventing a plausible-sounding paraphrase of scripture would be far worse. Agents render the row fine');
out.push('with an empty verse (they simply show the reference).');
out.push('');
out.push('**To fill these in:** open the Spanish scriptures, copy the wording exactly, and paste it into the');
out.push('`Scripture_Text` column. There are only ' + Object.keys(refs).length + ' distinct references — filling those in covers every blank row.');
out.push('');
out.push('| Referencia | Filas que la usan | Filas sin texto |');
out.push('|---|---|---|');
Object.keys(refs).sort().forEach((k) => out.push('| ' + k + ' | ' + refs[k].total + ' | ' + refs[k].blank + ' |'));
out.push('');
out.push('### 2. About the two brief-supplied example rows');
out.push('');
out.push('Two rows (**MSG-CS-ROLEPLAYS-01**, **MSG-CG-CONTACTS-01**) were originally seeded verbatim from the');
out.push('task brief\'s illustrative examples, including quoted verse wording and English-edition Predicad Mi');
out.push('Evangelio page numbers (`pág. 175`, `pág. 156`). Neither the quoted wording nor the page numbers could');
out.push('be verified against the Spanish LDS edition, so both rows were normalized to the same convention as');
out.push('every other row: chapter-level PMG reference, blank Scripture_Text. Their scripture *references*');
out.push('(`D. y C. 84:85`, `D. y C. 33:8-10`) were kept — only the quoted text and page numbers were dropped.');
out.push('');
out.push('### 3. Predicad Mi Evangelio references are chapter-level, never page-level');
out.push('');
out.push('Every row cites `Capítulo N` plus a one-line topic summary written for this system (not a quoted');
out.push('chapter title). This avoids guessing at Spanish-edition pagination. If mission leadership prefers page');
out.push('numbers from the Spanish edition, they can be added to the `PMG_Chapter` column.');
out.push('');
out.push('### 4. Carried forward from earlier tasks — still open');
out.push('');
out.push('- **Coaching KPI subset (Task 8).** Coaching emails display a curated 5-metric KPI subset, not all 25 metrics. Is that the right subset?');
out.push('- **`_LEADERSHIP_MSGS` (Task 8).** The leadership message bank was trimmed pending this content review.');
out.push('- **`ASC_DEFAULT_GOALS` (Task 12).** The weekly-count goal fallbacks are placeholder estimates, not mission-set targets. Until leadership sets real goals, FRIDAY_ENCOURAGEMENT fires against estimates.');
out.push('');
out.push('### 5. Tone and doctrine calls a mission president should confirm');
out.push('');
out.push('- **Form of address.** Every message addresses the *companionship* in ustedes-form, warm and direct. Titles are never used ("Elder"/"Hermana" appear nowhere), so a message reads the same to any companionship.');
out.push('- **No outcome promises.** No message says that doing X will produce a baptism or any other specific result. Growth messages name one concrete next step and stop there.');
out.push('- **No guilt.** MISSED_DAYS messages in particular are written as concern ("¿Cómo están por allá?"), never as reprimand. If leadership wants a firmer tone for repeated misses, that belongs in the escalation agent, not here.');
out.push('- **No statistics inside message text.** Messages say "esta semana su área se destacó" rather than quoting numbers; the numbers come from the surrounding email template, which is generated from real data.');
out.push('- **Names of Deity** used: Dios, Jesucristo, el Salvador, el Señor, el Espíritu Santo.');
out.push('- **Chilean usage.** "paradero" is used for bus stop (Chilean), and "amigos" is used throughout for those being taught, matching current Church usage. Please confirm both read naturally locally.');
out.push('');
out.push('---');
out.push('');
out.push('## MESSAGE_BANK');
out.push('');
CATS.forEach(([cat, title, blurb]) => {
  out.push('## ' + title);
  out.push('');
  out.push('_' + blurb + '_');
  out.push('');
  const rows = mb.filter((r) => r.Category === cat);
  const byMetric = {};
  rows.forEach((r) => { (byMetric[r.Metric] = byMetric[r.Metric] || []).push(r); });
  Object.keys(byMetric).forEach((m) => {
    if (m) out.push('### ' + (display[m] || m) + '  `' + m + '`');
    else out.push('### (sin métrica — se elige solo por categoría)');
    out.push('');
    byMetric[m].forEach((r) => {
      out.push('**' + r.Message_ID + '** — *' + r.Subject_Line + '*  ');
      out.push(r.Body_Text + '  ');
      const bits = [];
      if (r.PMG_Chapter) bits.push('Predicad Mi Evangelio, ' + r.PMG_Chapter + (r.PMG_Description ? ' — ' + r.PMG_Description : ''));
      if (r.Scripture) bits.push(r.Scripture + (r.Scripture_Text ? ': "' + r.Scripture_Text + '"' : ' _(texto pendiente)_'));
      if (bits.length) out.push('<sub>' + bits.join(' · ') + '</sub>');
      out.push('');
    });
  });
});
out.push('---');
out.push('');
out.push('## KNOWLEDGE_BASE');
out.push('');
out.push('_Read by `CCSM_AgentQA.gs` when a missionary emails a question. Gemini answers **from these rows only**._');
out.push('');
kb.forEach((r) => {
  out.push('**' + r.ID + '** (' + r.Category + ') — **' + r.Question + '**  ');
  out.push(r.Answer + '  ');
  out.push('<sub>Palabras clave: ' + r.Keywords + '</sub>');
  out.push('');
});

// ── LEADERSHIP MESSAGES (hardcoded in CCSM_Agent1C.gs) ──────────────────────
// Rendered from the live _LEADERSHIP_MSGS array rather than transcribed, so it
// cannot drift from what actually sends. These go to zone leaders, district
// leaders, APs and the mission president — a smaller audience than the bank
// rows, but a more consequential one.
const lead = scope._LEADERSHIP_MSGS || [];
const withText = lead.filter((m) => m.scriptText);

out.push('---');
out.push('');
out.push('## MENSAJES DE LIDERAZGO — `CCSM_Agent1C.gs` `_LEADERSHIP_MSGS`');
out.push('');
out.push('_Enviados a líderes de zona, líderes de distrito, APs y el presidente de misión._');
out.push('');
out.push('> ### ⚠️ ' + withText.length + ' de estas ' + lead.length + ' citas requieren verificación');
out.push('>');
out.push('> A diferencia de las ' + mb.length + ' filas de `MESSAGE_BANK` — que se envían con');
out.push('> `Scripture_Text` **en blanco** a propósito, porque nadie inventa la redacción de una');
out.push('> escritura — estos mensajes llevan el texto de la escritura **ya escrito**, y ese texto');
out.push('> fue redactado por un modelo, no copiado de la edición oficial en español.');
out.push('>');
out.push('> **Hay al menos dos referencias mal atribuidas** (el texto citado no corresponde al');
out.push('> versículo indicado). Verifique CADA cita contra la edición oficial en español:');
out.push('> confirme la referencia, luego confirme la redacción palabra por palabra.');
out.push('>');
out.push('> Los números de página de *Predicad Mi Evangelio* provienen de la edición en inglés');
out.push('> y también deben verificarse.');
out.push('');
out.push('| # | Tema | Escritura | Texto citado | PMG |');
out.push('|---|---|---|---|---|');
lead.forEach((m, i) => {
  out.push('| ' + (i + 1) + ' | ' + m.theme + ' | **' + (m.scripture || '—') + '** | ' +
    (m.scriptText ? '⚠️ verificar' : '_(en blanco)_') + ' | ' + (m.pmg || '—') + ' |');
});
out.push('');

lead.forEach((m, i) => {
  out.push('#### ' + (i + 1) + '. ' + m.theme + ' — ' + m.subject);
  out.push('');
  out.push(m.body + '  ');
  const bits = [];
  if (m.pmg) bits.push('Predicad Mi Evangelio, p. ' + m.pmg + ' _(página de la edición en inglés — verificar)_');
  if (m.scripture) {
    bits.push('**' + m.scripture + '**' +
      (m.scriptText ? ': "' + m.scriptText + '" ⚠️ _verificar referencia y redacción_'
                    : ' _(texto pendiente)_'));
  }
  if (bits.length) out.push('<sub>' + bits.join(' · ') + '</sub>');
  out.push('');
});

const md = out.join('\n');
fs.writeFileSync('CONTENT_REVIEW.md', md, 'utf8');
console.log('CONTENT_REVIEW.md written — ' + md.split('\n').length + ' lines');
